exclude: ^$
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-ast
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: flake8

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  - id: codespell
    exclude_types: [json]
    args: [-L connexion]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    exclude: ^(tests/)
    language: system
    types: [python]

# - repo: local
#   hooks:
#   - id: coverage-local
#     name: coverage
#     always_run: true
#     entry: ./scripts/coverage.sh 100
#     language: script
#     pass_filenames: false

- repo: https://github.com/marco-c/taskcluster_yml_validator
  rev: v0.0.7
  hooks:
  - id: taskcluster_yml

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    exclude: ^(tests/)
    args: [--no-strict-optional, --ignore-missing-imports]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: meta
  hooks:
  - id: check-useless-excludes
default_language_version:
  python: python3.9
default_stages: [commit, push]
